services:
  mysql:
    image: mysql:8.0
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - mysql-vol:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: 'mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}'
      interval: 1s
      timeout: 1s
      retries: 60
  adminer:
    image: adminer
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql

volumes:
  mysql-vol:
